import { Schema, model, models, type InferSchemaType } from 'mongoose'

const ticketCommentSchema = new Schema(
  {
    ticketId: { type: Schema.Types.ObjectId, ref: 'Ticket', required: true },
    authorId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    body: { type: String, required: true }, // sanitized HTML
    isInternal: { type: Boolean, default: false },
    // 'questionnaire' comments are auto-generated by submitQuestionnaireAction: `body` holds a
    // short plain summary, and the full structured answers render from the linked
    // TicketQuestionnaire doc (see QuestionnaireResponseCard) rather than from stored HTML —
    // the sanitizeHtml allowlist doesn't permit the table/div markup a rendered response needs.
    kind: { type: String, enum: ['comment', 'questionnaire'], default: 'comment' },
    questionnaireId: { type: Schema.Types.ObjectId, ref: 'TicketQuestionnaire', default: null },
    editedAt: { type: Date, default: null },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true },
)

ticketCommentSchema.index({ ticketId: 1, createdAt: 1 })

export type TicketComment = InferSchemaType<typeof ticketCommentSchema>
export const TicketCommentModel =
  models.TicketComment ?? model('TicketComment', ticketCommentSchema)
